### ISSUE TITLE
Submission checklist

### ISSUE THREAD

**Issue by cyrillustan** [meyer-lab/systemsSerology#243]
IMPORTANT: When you send your revision, we will require the following items: 

- [x] 1. the manuscript text in LaTeX, RTF or MS Word format 

- [x] 2. a letter with a detailed description of the changes made in response to the referees. Please specify clearly the exact places in the text (pages and paragraphs) where each change has been made in response to each specific comment given 

- [x] 3. three to four 'bullet points' highlighting the main findings of your study 

- [x] 4. a short 'blurb' text summarizing in two sentences the study (max. 250 characters) 

- [ ] 5. a 'thumbnail image' (550px width and max 400px height, Illustrator, PowerPoint or jpeg format), which can be used as 'visual title' for the synopsis section of your paper. 

- [x] 6. Please include an author contributions statement after the Acknowledgments section (see https://www.embopress.org/page/journal/17444292/authorguide) 

- [x] 7. Please complete the CHECKLIST available at (https://bit.ly/EMBOPressAuthorChecklist). 

Please note that the Author Checklist will be published alongside the paper as part of the transparent process (https://www.embopress.org/page/journal/17444292/authorguide#transparentprocess). 

- [x] 8. Please note that corresponding authors are required to supply an ORCID ID for their name upon submission of a revised manuscript (EMBO Press signed a joint statement to encourage ORCID adoption). (https://www.embopress.org/page/journal/17444292/authorguide#editorialprocess)
